services:
  - type: web
    name: vertex-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://vertex-web-9e98.onrender.com,https://vertex.ademyahmadi.com
      - key: MAX_UPLOAD_MB
        value: "15"

  - type: web
    name: vertex-web
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://vertex-api-lri2.onrender.com/scan
      - key: VITE_HOSTED
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
